[package]
name = "cc26x0"
version = "0.1.0"
authors = ["Tock Project Developers <tock-dev@googlegroups.com>"]

[dependencies]
cortexm3 = { path = "../../arch/cortex-m3" }
kernel = { path = "../../kernel" }
bitfield = "0.11.0"
cc26xx = { path = "../cc26xx" }
